development:
  paypal_email: bilton2@paypal.com
  paypal_secret: secret
  paypal_cert_id: HTVRWVBT9HLUU
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl

production:
  paypal_email: bilton2@paypal.com
  paypal_secret: secret
  paypal_cert_id: HTVRWVBT9HLUU
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"