# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72e59b5cb8e9300376dffa9a9cdee3bed79b76b1c119b7bb0091a3ed67d4438db1e5e364a728ccedb8b4c9be5c49e65fb1edc6b02439fdc64f10a5517b61fd45

test:
  secret_key_base: 0e90cd96d34d8397a39d38a0063093dd1bc7b26110b51fff6f52b3f2440a4235f6cd7eb789a2c7366f6f9d08d7b54939069ed2bc2b33afdf2715208e84c76a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
